name: 배포 to EC2

on:
  push:
    branches: 
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH(원격 접속)로 EC2에 접속하기
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USERNAME}}
        key: ${{secrets.EC2_PRIVATE_KEY}}
        script_stop: true
        script: |
          cd /home/ubuntu/online_food_ordering
          git pull origin main
          cd Server/food-ordering-system
          ./gradelw spotlessApply
          ./gradlew clean build -x test
          sudo fuser -k -n tcp 5454 || true
          nohup java -jar build/libs/*SNAPSHOT.war > ./output.log 2>&1 &
